- hosts: localhost
  #vars:
   #  ansible_python_interpreter: /usr/bin/python2.7
  vars_files:
  
  tasks:  
  - name: confguring repo for K8s
    shell:  |
                cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
                [kubernetes]
                name=Kubernetes
                baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                enabled=1
                gpgcheck=1
                repo_gpgcheck=1
                gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                EOF
  - name: "configuring repo for docker"
    yum_repository:
            baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
            description: Repo for docker
            gpgcheck: no 
            name: docker
            
  - name: installing docker
    package:
            name: "docker-ce-3:18.09.1-3.el7.x86_64"
            state: present
  - name: "deleting repo for docker"
    file:
            path: "/etc/yum.repos.d/docker.repo"
            state: absent

  - name: "starting the docker service"
    service: 
        name: "docker"
        state: started
        enabled: yes
  
  - name: "installing kubeadm"
    package:
         name: "kubeadm"
         state: present
  
  - name: "starting the kubelet service"
    service: 
         name: "kubelet"
         state: started
         enabled: yes
  
  - name: "pulling all the docker images for cluster"
    command: "kubeadm config images pull"
  
  - name: "setting up driver docker cgroup to use systemd instead of cgroupfs"
    copy:
         dest: "/etc/docker/daemon.json"
         content: '{
                   "exec-opts": ["native.cgroupdriver=systemd"]
                   }'
  
  - name: "restarting docker service"
    service:
         name: "docker"
         state: restarted
  
  - name: "installing iproute-tc software for traffic control"
    package:  
         name: "iproute-tc"
         state: present       

  - name: "creating a file"
    file:
            path: "/etc/sysctl.d/k8s.conf"
            state: touch
            group: "root"
            owner: "root"
            mode: 0644  
    become: yes
    become_user: root
    become_method: sudo
  
  - name: "network configuration"
    blockinfile: 
        path: "/etc/sysctl.d/k8s.conf"
        block: |
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables = 1
        state: present
  
  - name: " Starting sysctl service"
    command: "sysctl --system"
    become: yes
    become_user: root
    become_method: sudo
  
  - name: "Ignoring RAM and CPU errors(system requirements)"
    shell: "kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem --ignore-preflight-errors=Swap"
    environment:
            KUBECONFIG: "/etc/kubernetes/admin.conf"

  - name: "Running flannel pod "
    command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"  
